/* Auto-generated by: https://github.com/pmndrs/gltfjsx
   Command: npx gltfjsx@6.5.3 earth.glb -t
   Author: Meee (https://sketchfab.com/Meee)
   License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
   Source: https://sketchfab.com/3d-models/earth-hologram-87072288fb234226b9a3f02ae674a310
   Title: Earth hologram */

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type ActionName = 'Take 01'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    
    Sphere002_0: THREE.Mesh
    Circle643_0: THREE.Mesh
    Circle455_0: THREE.Mesh
    Icosphere002_0: THREE.Mesh
    Circle_0: THREE.Mesh
  }
  materials: {
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Earth(props: React.ComponentProps<'group'>) {
  const group = React.useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/models/earth.glb') as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)

  // Optional: Start animation on mount
  React.useEffect(() => {
    if (actions['Take 01']) {
      actions['Take 01']?.play()
    }
  }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.306}>
          <group name="Root">

            <group name="Sphere002" rotation={[0, 0, -3.015]} scale={0.965}>
              <mesh name="Sphere002_0" geometry={nodes.Sphere002_0.geometry} material={materials['Material.006']} />
            </group>
            <group name="Circle643" scale={4.787}>
              <mesh name="Circle643_0" geometry={nodes.Circle643_0.geometry} material={materials['Material.004']} />
            </group>
            <group name="Circle455" scale={0.176}>
              <mesh 
                name="Circle455_0" 
                geometry={nodes.Circle455_0.geometry} 
                material={materials['Material.007']} 
                morphTargetDictionary={nodes.Circle455_0.morphTargetDictionary} 
                morphTargetInfluences={nodes.Circle455_0.morphTargetInfluences} 
              />
            </group>
            <group name="Circle" scale={6.128}>
              <group name="Icosphere002" position={[1, 0, 0]} scale={0.063}>
                <mesh name="Icosphere002_0" geometry={nodes.Icosphere002_0.geometry} material={materials['Material.008']} />
              </group>
              <mesh name="Circle_0" geometry={nodes.Circle_0.geometry} material={materials['Material.010']} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/earth.glb')