/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 isometric_room.glb -t 
Author: darkpro1337 (https://sketchfab.com/darkpro1337)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/isometric-room-09e0a182cc4b4f05a241f165026691f6
Title: Isometric Room
*/

import * as THREE from 'three'

import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import type { JSX } from 'react/jsx-dev-runtime'

type GLTFResult = GLTF & {
  nodes: {
    Cube_4_Mat13_0: THREE.Mesh
    Cube_3_Mat13_0: THREE.Mesh
    Plane_Mat12_0: THREE.Mesh
    Cube_1_Mat10_0: THREE.Mesh
    Cube_2_Mat11_0: THREE.Mesh
    Cube_Window_0: THREE.Mesh
    Cube_Mat11_0: THREE.Mesh
    Cube__0: THREE.Mesh
    Cube_7_Buttons_0: THREE.Mesh
    Cube_1_2_Buttons_0: THREE.Mesh
    Cube_6_Buttons_0: THREE.Mesh
    Cube_3_2_Buttons_0: THREE.Mesh
    Cube_5_Buttons_0: THREE.Mesh
    Cube_4_2_Buttons_0: THREE.Mesh
    Cube_2_2_Buttons_0: THREE.Mesh
    Cube_2_3_Buttons_0: THREE.Mesh
    Cube_7_2_Buttons_0: THREE.Mesh
    Cube_6_2_Buttons_0: THREE.Mesh
    Cube_3_3_Buttons_0: THREE.Mesh
    Cube_5_2_Buttons_0: THREE.Mesh
    Cube_4_3_Buttons_0: THREE.Mesh
    Cube_2_4_Buttons_0: THREE.Mesh
    Cube_3_4_Buttons_0: THREE.Mesh
    Switch_2_Left_0: THREE.Mesh
    Switch_2_Right_0: THREE.Mesh
    Switch_2_Mat7_0: THREE.Mesh
    Switch_2_Buttons_0: THREE.Mesh
    Table_3_Table_0: THREE.Mesh
    Table_2_Table_0: THREE.Mesh
    Table_1_Table_0: THREE.Mesh
    Cylinder_Keyboard_0: THREE.Mesh
    Cylinder_2_Mat5_0: THREE.Mesh
    Cylinder_2_Mat4_0: THREE.Mesh
    Cylinder_2__0: THREE.Mesh
    Lamp_2_Lamp_0: THREE.Mesh
    Lamp_2_Lamp1_0: THREE.Mesh
    Pen_tablet_PenTablet_0: THREE.Mesh
    Pen_holder_PenTablet_0: THREE.Mesh
    Tablet_2_PenTablet_0: THREE.Mesh
    Tablet_2_PenTablet1_0: THREE.Mesh
    Router_2_Mat1_0: THREE.Mesh
    Router_2_Mat2_0: THREE.Mesh
    Box_2_2_Box_0: THREE.Mesh
    Box_Box_0: THREE.Mesh
    Cylinder_3_Mat_0: THREE.Mesh
    Cylinder_1_Water_0: THREE.Mesh
    Cube_2_5_Book3_0: THREE.Mesh
    Cube_2_5_Book_0: THREE.Mesh
    Cube_1_3_Book2_0: THREE.Mesh
    Cube_1_3_Book_0: THREE.Mesh
    Cube_4_4_Book1_0: THREE.Mesh
    Cube_4_4_Book_0: THREE.Mesh
    Cube_2_6_Book3_0: THREE.Mesh
    Cube_2_6_Book_0: THREE.Mesh
    Cube_1_4_Book2_0: THREE.Mesh
    Cube_1_4_Book_0: THREE.Mesh
    Cube_5_3_Book1_0: THREE.Mesh
    Cube_5_3_Book_0: THREE.Mesh
    Cube_3_5_Monitor_Color_0: THREE.Mesh
    Cube_4_5_Monitor_Color_0: THREE.Mesh
    Cube_4_5_Monitor_0: THREE.Mesh
    Cube_2_7_Monitor_Color1_0: THREE.Mesh
    Cube_2_8_Monitor_Color1_0: THREE.Mesh
    Cube_2_8__0: THREE.Mesh
    Cube_2_8_Monitor_Color_0: THREE.Mesh
    Cube_3_6_Monitor_Color1_0: THREE.Mesh
    Cube_3_6_Monitor_0: THREE.Mesh
    Cube_6_3_Monitor_Color1_0: THREE.Mesh
    Cube_1_5_Monitor_Color1_0: THREE.Mesh
    Cube_7_3_Monitor_Color1_0: THREE.Mesh
    Cube_3_7_Monitor_Color1_0: THREE.Mesh
    Cylinder_4_Mouse_0: THREE.Mesh
    Cube_8_Mouse_0: THREE.Mesh
    Cube_2_9_Keyboard_0: THREE.Mesh
    Cube_1_6_Keyboard_0: THREE.Mesh
    Cube_5_4_Monitor1_0: THREE.Mesh
    Cube_4_6_Monitor1_0: THREE.Mesh
    Cube_3_8_Keyboard_0: THREE.Mesh
    Cube_1_0_Keyboard_0: THREE.Mesh
    Cube_1_1_Keyboard_0: THREE.Mesh
    Cube_1_2_2_Keyboard_0: THREE.Mesh
    Cube_1_3_2_Keyboard_0: THREE.Mesh
    Cube_1_4_2_Keyboard_0: THREE.Mesh
    Cube_1_5_2_Keyboard_0: THREE.Mesh
    Cube_1_6_2_Keyboard_0: THREE.Mesh
    Cube_1_7_Keyboard_0: THREE.Mesh
    Cube_1_8_Keyboard_0: THREE.Mesh
    Cube_1_9_Keyboard_0: THREE.Mesh
    Cube_1_10_Keyboard_0: THREE.Mesh
    Cube_1_11_Keyboard_0: THREE.Mesh
    Cube_1_12_Keyboard_0: THREE.Mesh
    Cube_1_13_Keyboard_0: THREE.Mesh
    Cube_1_14_Keyboard_0: THREE.Mesh
    Cube_1_15_Keyboard_0: THREE.Mesh
    Cube_1_16_Keyboard_0: THREE.Mesh
    Cube_1_17_Keyboard_0: THREE.Mesh
    Cube_1_18_Keyboard_0: THREE.Mesh
    Cube_1_19_Keyboard_0: THREE.Mesh
    Cube_1_20_Keyboard_0: THREE.Mesh
    Cube_1_21_Keyboard_0: THREE.Mesh
    Cube_1_22_Keyboard_0: THREE.Mesh
    Cube_1_23_Keyboard_0: THREE.Mesh
    Cube_1_24_Keyboard_0: THREE.Mesh
    Cube_1_25_Keyboard_0: THREE.Mesh
    Cube_1_26_Keyboard_0: THREE.Mesh
    Cube_1_27_Keyboard_0: THREE.Mesh
    Cube_1_28_Keyboard_0: THREE.Mesh
    Cube_1_29_Keyboard_0: THREE.Mesh
    Cube_1_30_Keyboard_0: THREE.Mesh
    Cube_1_31_Keyboard_0: THREE.Mesh
    Cube_1_32_Keyboard_0: THREE.Mesh
    Cube_1_33_Keyboard_0: THREE.Mesh
    Cube_1_34_Keyboard_0: THREE.Mesh
    Cube_1_35_Keyboard_0: THREE.Mesh
    Cube_1_36_Keyboard_0: THREE.Mesh
    Cube_1_37_Keyboard_0: THREE.Mesh
    Cube_1_38_Keyboard_0: THREE.Mesh
    Cube_1_39_Keyboard_0: THREE.Mesh
    Cube_1_40_Keyboard_0: THREE.Mesh
    Cube_1_41_Keyboard_0: THREE.Mesh
    Cube_1_42_Keyboard_0: THREE.Mesh
    Cube_1_43_Keyboard_0: THREE.Mesh
    Cube_1_44_Keyboard_0: THREE.Mesh
    Cube_1_45_Keyboard_0: THREE.Mesh
    Cube_1_46_Keyboard_0: THREE.Mesh
    Cube_1_47_Keyboard_0: THREE.Mesh
    Cube_1_48_Keyboard_0: THREE.Mesh
    Cube_1_49_Keyboard_0: THREE.Mesh
    Cube_1_50_Keyboard_0: THREE.Mesh
    Cube_1_51_Keyboard_0: THREE.Mesh
    Cube_1_52_Keyboard_0: THREE.Mesh
    Cube_1_53_Keyboard_0: THREE.Mesh
    Cube_1_54_Keyboard_0: THREE.Mesh
    Cube_1_55_Keyboard_0: THREE.Mesh
    Cube_1_56_Keyboard_0: THREE.Mesh
    Cube_1_57_Keyboard_0: THREE.Mesh
    Cube_1_58_Keyboard_0: THREE.Mesh
    Cube_1_59_Keyboard_0: THREE.Mesh
    Cube_1_60_Keyboard_0: THREE.Mesh
    Cube_1_61_Keyboard_0: THREE.Mesh
    Cube_1_62_Keyboard_0: THREE.Mesh
    Cube_1_63_Keyboard_0: THREE.Mesh
    Cube_1_64_Keyboard_0: THREE.Mesh
    Cube_1_65_Keyboard_0: THREE.Mesh
    Cube_1_66_Keyboard_0: THREE.Mesh
    Cube_1_67_Keyboard_0: THREE.Mesh
    Cube_1_68_Keyboard_0: THREE.Mesh
    Cube_1_69_Keyboard_0: THREE.Mesh
    Cube_1_70_Keyboard_0: THREE.Mesh
    Cube_1_71_Keyboard_0: THREE.Mesh
    Cube_1_72_Keyboard_0: THREE.Mesh
    Cube_1_73_Keyboard_0: THREE.Mesh
    Cube_1_74_Keyboard_0: THREE.Mesh
    Cube_1_75_Keyboard_0: THREE.Mesh
    Cube_1_76_Keyboard_0: THREE.Mesh
    Cube_1_77_Keyboard_0: THREE.Mesh
    Cube_1_78_Keyboard_0: THREE.Mesh
    Cube_1_79_Keyboard_0: THREE.Mesh
    Cube_1_80_Keyboard_0: THREE.Mesh
    Cube_1_81_Keyboard_0: THREE.Mesh
    Cube_1_82_Keyboard_0: THREE.Mesh
    Cube_1_83_Keyboard_0: THREE.Mesh
    Cube_1_84_Keyboard_0: THREE.Mesh
    Cube_1_85_Keyboard_0: THREE.Mesh
    Cube_1_86_Keyboard_0: THREE.Mesh
    Cube_1_87_Keyboard_0: THREE.Mesh
    Cube_1_88_Keyboard_0: THREE.Mesh
    Cube_1_89_Keyboard_0: THREE.Mesh
    Cube_9_Keyboard_0: THREE.Mesh
    Cylinder_5_Chair_0: THREE.Mesh
    Cylinder_4_2_Chair_0: THREE.Mesh
    Cylinder_3_2_Chair_0: THREE.Mesh
    Cylinder_2_2_Chair_0: THREE.Mesh
    Cylinder_1_2_Chair_0: THREE.Mesh
    Capsule_Chair1_0: THREE.Mesh
    Cube_10_Chair_0: THREE.Mesh
    Sphere_Chair1_0: THREE.Mesh
    Cylinder_5_2_Chair_0: THREE.Mesh
    Cylinder_0_Chair_0: THREE.Mesh
    Cylinder_1_3_Chair_0: THREE.Mesh
    Cylinder_2_3_Chair_0: THREE.Mesh
    Cylinder_3_3_Chair_0: THREE.Mesh
    Cylinder_4_3_Chair_0: THREE.Mesh
    Cube_11_Shelf_0: THREE.Mesh
    Cube_1_7_2_Shelf_0: THREE.Mesh
    Cube_12_Shelf_0: THREE.Mesh
    Cube_1_8_2_Shelf_0: THREE.Mesh
    Table_1_2_Table_0: THREE.Mesh
    Table_2_2_Table_0: THREE.Mesh
    Table_4_Table_0: THREE.Mesh
    Hole_Table_0: THREE.Mesh
    Cube_13_Window_0: THREE.Mesh
    Cube_1_9_2_Window_0: THREE.Mesh
    Glass_Glass_0: THREE.Mesh
    Frame_Window_0: THREE.Mesh
    Hole_2_Window_0: THREE.Mesh
    Room_2_Room_0: THREE.Mesh
    Window_Hole_Room_0: THREE.Mesh
  }
  materials: {
    ['Mat.13']: THREE.MeshStandardMaterial
    ['Mat.13_0']: THREE.MeshStandardMaterial
    ['Mat.12']: THREE.MeshStandardMaterial
    ['Mat.10']: THREE.MeshStandardMaterial
    ['Mat.11']: THREE.MeshStandardMaterial
    Window: THREE.MeshStandardMaterial
    Cube__0: THREE.MeshStandardMaterial
    Buttons: THREE.MeshStandardMaterial
    Left: THREE.MeshStandardMaterial
    Right: THREE.MeshStandardMaterial
    ['Mat.7']: THREE.MeshStandardMaterial
    Table: THREE.MeshStandardMaterial
    Keyboard: THREE.MeshStandardMaterial
    ['Mat.5']: THREE.MeshStandardMaterial
    ['Mat.4']: THREE.MeshStandardMaterial
    Lamp: THREE.MeshStandardMaterial
    ['Lamp.1']: THREE.MeshStandardMaterial
    PenTablet: THREE.MeshStandardMaterial
    ['PenTablet.1']: THREE.MeshStandardMaterial
    ['Mat.1']: THREE.MeshStandardMaterial
    ['Mat.2']: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    material_22: THREE.MeshStandardMaterial
    Water: THREE.MeshStandardMaterial
    ['Book.3']: THREE.MeshStandardMaterial
    Book: THREE.MeshStandardMaterial
    ['Book.2']: THREE.MeshStandardMaterial
    ['Book.1']: THREE.MeshStandardMaterial
    Monitor_Color: THREE.MeshStandardMaterial
    Monitor: THREE.MeshStandardMaterial
    ['Monitor_Color.1']: THREE.MeshStandardMaterial
    Mouse: THREE.MeshStandardMaterial
    ['Monitor.1']: THREE.MeshStandardMaterial
    Chair: THREE.MeshStandardMaterial
    ['Chair.1']: THREE.MeshStandardMaterial
    Shelf: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
    Room: THREE.MeshStandardMaterial
  }
  animations:THREE.AnimationClip[]
}

export function Room(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/isometric_room.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[148.62, 39.735, 64.427]}>
        <mesh geometry={nodes.Cube_Window_0.geometry} material={materials.Window} />
        <mesh geometry={nodes.Cube_Mat11_0.geometry} material={materials['Mat.11']} />
        <mesh geometry={nodes.Cube__0.geometry} material={materials.Cube__0} />
      </group>
      <group position={[-98.974, 95.02, 17.711]}>
        <group position={[-0.04, 0.162, -7.362]}>
          <mesh geometry={nodes.Cube_7_Buttons_0.geometry} material={materials.Buttons} position={[2.508, 0, 0.771]} />
          <mesh geometry={nodes.Cube_1_2_Buttons_0.geometry} material={materials.Buttons} position={[-2.903, 0, 0.835]} rotation={[0, -Math.PI / 2, 0]} />
          <mesh geometry={nodes.Cube_6_Buttons_0.geometry} material={materials.Buttons} position={[-2.903, 0, 0.835]} />
          <mesh geometry={nodes.Cube_3_2_Buttons_0.geometry} material={materials.Buttons} position={[1.168, 0, 0.229]} />
          <mesh geometry={nodes.Cube_5_Buttons_0.geometry} material={materials.Buttons} position={[-0.34, 0, 0.229]} />
          <mesh geometry={nodes.Cube_4_2_Buttons_0.geometry} material={materials.Buttons} position={[-1.696, 0, 0.229]} />
          <mesh geometry={nodes.Cube_2_2_Buttons_0.geometry} material={materials.Buttons} position={[-1.032, 0, -0.457]} />
          <mesh geometry={nodes.Cube_2_3_Buttons_0.geometry} material={materials.Buttons} position={[-1.032, 0, 0.902]} />
        </group>
        <group position={[-0.04, 0.162, 7.015]}>
          <mesh geometry={nodes.Cube_7_2_Buttons_0.geometry} material={materials.Buttons} position={[2.508, 0, -0.543]} />
          <mesh geometry={nodes.Cube_6_2_Buttons_0.geometry} material={materials.Buttons} position={[-2.903, 0, -0.588]} />
          <mesh geometry={nodes.Cube_3_3_Buttons_0.geometry} material={materials.Buttons} position={[-1.653, 0, 0.229]} />
          <mesh geometry={nodes.Cube_5_2_Buttons_0.geometry} material={materials.Buttons} position={[1.197, 0, 0.229]} />
          <mesh geometry={nodes.Cube_4_3_Buttons_0.geometry} material={materials.Buttons} position={[-0.159, 0, 0.229]} />
          <mesh geometry={nodes.Cube_2_4_Buttons_0.geometry} material={materials.Buttons} position={[0.505, 0, -0.457]} />
          <mesh geometry={nodes.Cube_3_4_Buttons_0.geometry} material={materials.Buttons} position={[0.505, 0, 0.902]} />
        </group>
        <group position={[0.04, -0.162, 0.174]}>
          <mesh geometry={nodes.Switch_2_Left_0.geometry} material={materials.Left} />
          <mesh geometry={nodes.Switch_2_Right_0.geometry} material={materials.Right} />
          <mesh geometry={nodes.Switch_2_Mat7_0.geometry} material={materials['Mat.7']} />
          <mesh geometry={nodes.Switch_2_Buttons_0.geometry} material={materials.Buttons} />
        </group>
      </group>
      <group position={[-142.365, 170.852, 70.286]}>
        <mesh geometry={nodes.Table_3_Table_0.geometry} material={materials.Table} position={[0, 0, -39.76]} />
        <mesh geometry={nodes.Table_2_Table_0.geometry} material={materials.Table} position={[0, 0, 40.046]} />
        <mesh geometry={nodes.Table_1_Table_0.geometry} material={materials.Table} position={[0, 0, -0.286]} />
      </group>
      <group position={[-124.843, 102.865, 106.494]} rotation={[0, -0.745, 0]}>
        <mesh geometry={nodes.Cylinder_Keyboard_0.geometry} material={materials.Keyboard} />
        <mesh geometry={nodes.Cylinder_2_Mat5_0.geometry} material={materials['Mat.5']} />
        <mesh geometry={nodes.Cylinder_2_Mat4_0.geometry} material={materials['Mat.4']} />
        <mesh geometry={nodes.Cylinder_2__0.geometry} material={materials.Cube__0} />
      </group>
      <group position={[-130.161, 94.99, 26.525]} rotation={[0, -0.194, 0]}>
        <mesh geometry={nodes.Lamp_2_Lamp_0.geometry} material={materials.Lamp} />
        <mesh geometry={nodes.Lamp_2_Lamp1_0.geometry} material={materials['Lamp.1']} />
      </group>
      <group position={[-111.03, 95.566, 118.376]} rotation={[0, 0.386, 0]}>
        <group position={[3.856, -0.901, 9.58]}>
          <mesh geometry={nodes.Tablet_2_PenTablet_0.geometry} material={materials.PenTablet} />
          <mesh geometry={nodes.Tablet_2_PenTablet1_0.geometry} material={materials['PenTablet.1']} />
        </group>
        <mesh geometry={nodes.Pen_tablet_PenTablet_0.geometry} material={materials.PenTablet} position={[-1.928, 1.398, -4.79]} />
        <mesh geometry={nodes.Pen_holder_PenTablet_0.geometry} material={materials.PenTablet} position={[-1.928, -0.497, -4.79]} />
      </group>
      <group position={[-147.983, 95.505, 43.402]}>
        <mesh geometry={nodes.Router_2_Mat1_0.geometry} material={materials['Mat.1']} />
        <mesh geometry={nodes.Router_2_Mat2_0.geometry} material={materials['Mat.2']} />
      </group>
      <mesh geometry={nodes.Box_2_2_Box_0.geometry} material={materials.material} position={[-142.365, 178.515, 129.234]} />
      <mesh geometry={nodes.Box_Box_0.geometry} material={materials.material} position={[-135.075, 136.814, 2.473]} rotation={[Math.PI, -Math.PI / 3, Math.PI]} />
      <group position={[-113.637, 96.791, 27.519]} rotation={[0, -0.428, 0]}>
        <mesh geometry={nodes.Cylinder_3_Mat_0.geometry} material={materials.material_22} />
        <mesh geometry={nodes.Cylinder_1_Water_0.geometry} material={materials.Water} />
      </group>
      <group position={[-136.126, 176.519, -0.568]} rotation={[Math.PI, 0.657, -Math.PI]}>
        <group position={[0, 2.112, 0]} rotation={[0, -0.047, 0]}>
          <mesh geometry={nodes.Cube_2_5_Book3_0.geometry} material={materials['Book.3']} />
          <mesh geometry={nodes.Cube_2_5_Book_0.geometry} material={materials.Book} />
        </group>
        <group position={[0, 0.002, 0]} rotation={[0, 0.037, 0]}>
          <mesh geometry={nodes.Cube_1_3_Book2_0.geometry} material={materials['Book.2']} />
          <mesh geometry={nodes.Cube_1_3_Book_0.geometry} material={materials.Book} />
        </group>
        <group position={[0, -2.114, 0]} rotation={[0, -0.053, 0]}>
          <mesh geometry={nodes.Cube_4_4_Book1_0.geometry} material={materials['Book.1']} />
          <mesh geometry={nodes.Cube_4_4_Book_0.geometry} material={materials.Book} />
        </group>
      </group>
      <group position={[-130.212, 98.733, 8.909]} rotation={[0, -0.036, 0]}>
        <group position={[0, 2.112, 0]} rotation={[0, -0.047, 0]}>
          <mesh geometry={nodes.Cube_2_6_Book3_0.geometry} material={materials['Book.3']} />
          <mesh geometry={nodes.Cube_2_6_Book_0.geometry} material={materials.Book} />
        </group>
        <group position={[0, 0.002, 0]} rotation={[0, 0.037, 0]}>
          <mesh geometry={nodes.Cube_1_4_Book2_0.geometry} material={materials['Book.2']} />
          <mesh geometry={nodes.Cube_1_4_Book_0.geometry} material={materials.Book} />
        </group>
        <group position={[0, -2.114, 0]} rotation={[0, -0.053, 0]}>
          <mesh geometry={nodes.Cube_5_3_Book1_0.geometry} material={materials['Book.1']} />
          <mesh geometry={nodes.Cube_5_3_Book_0.geometry} material={materials.Book} />
        </group>
      </group>
      <group position={[-71.682, 57.474, 57.828]} rotation={[0.012, 0, 0]}>
        <group position={[-58.335, 59.133, 62.937]} rotation={[0, Math.PI / 6, -Math.PI / 2]}>
          <mesh geometry={nodes.Cube_4_5_Monitor_Color_0.geometry} material={materials.Monitor_Color} />
          <mesh geometry={nodes.Cube_4_5_Monitor_0.geometry} material={materials.Monitor} />
        </group>
        <mesh geometry={nodes.Cube_3_5_Monitor_Color_0.geometry} material={materials.Monitor_Color} position={[-59.869, 58.658, 63.823]} rotation={[0, Math.PI / 6, -Math.PI / 2]} />
        <mesh geometry={nodes.Cube_2_7_Monitor_Color1_0.geometry} material={materials['Monitor_Color.1']} position={[-63.68, 38.022, 66.036]} rotation={[0, Math.PI / 6, 0]} />
      </group>
      <group position={[-73.524, 62.254, 40.524]}>
        <group position={[-68.991, 53.865, 40.524]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.Cube_2_8_Monitor_Color1_0.geometry} material={materials['Monitor_Color.1']} />
          <mesh geometry={nodes.Cube_2_8__0.geometry} material={materials.Cube__0} />
          <mesh geometry={nodes.Cube_2_8_Monitor_Color_0.geometry} material={materials.Monitor_Color} />
        </group>
        <group position={[-67.165, 55.234, 40.524]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.Cube_3_6_Monitor_Color1_0.geometry} material={materials['Monitor_Color.1']} />
          <mesh geometry={nodes.Cube_3_6_Monitor_0.geometry} material={materials.Monitor} />
        </group>
        <group position={[73.524, -42.815, -40.524]}>
          <mesh geometry={nodes.Cube_7_3_Monitor_Color1_0.geometry} material={materials['Monitor_Color.1']} position={[-143.875, 76.045, 81.048]} />
          <mesh geometry={nodes.Cube_3_7_Monitor_Color1_0.geometry} material={materials['Monitor_Color.1']} position={[-143.138, 76.045, 81.048]} />
        </group>
        <mesh geometry={nodes.Cube_6_3_Monitor_Color1_0.geometry} material={materials['Monitor_Color.1']} position={[-71.945, 45.643, 40.524]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.Cube_1_5_Monitor_Color1_0.geometry} material={materials['Monitor_Color.1']} position={[-75.104, 39.987, 40.524]} rotation={[0, 0, -0.315]} />
      </group>
      <group position={[-115.647, 96.256, 45.125]} rotation={[0, -0.207, 0]}>
        <mesh geometry={nodes.Cylinder_4_Mouse_0.geometry} material={materials.Mouse} position={[-2.161, 0.772, -0.002]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={0.9} />
        <mesh geometry={nodes.Cube_8_Mouse_0.geometry} material={materials.Mouse} position={[2.161, -0.772, 0.002]} />
      </group>
      <group position={[-118.777, 96.844, 81.409]} rotation={[0, 0.172, -0.175]}>
        <group position={[-3.208, 0.672, -17.366]}>
          <mesh geometry={nodes.Cube_5_4_Monitor1_0.geometry} material={materials['Monitor.1']} position={[0, 0, 1.214]} />
          <mesh geometry={nodes.Cube_4_6_Monitor1_0.geometry} material={materials['Monitor.1']} position={[0, 0, 0.014]} />
          <mesh geometry={nodes.Cube_3_8_Keyboard_0.geometry} material={materials.Keyboard} position={[0, 0, -1.229]} />
        </group>
        <group position={[3.87, 0.592, -0.409]}>
          <mesh geometry={nodes.Cube_1_0_Keyboard_0.geometry} material={materials.Keyboard} position={[-5, 0, 19]} />
          <mesh geometry={nodes.Cube_1_1_Keyboard_0.geometry} material={materials.Keyboard} position={[-2.5, 0, 19]} />
          <mesh geometry={nodes.Cube_1_2_2_Keyboard_0.geometry} material={materials.Keyboard} position={[0, 0, 19]} />
          <mesh geometry={nodes.Cube_1_3_2_Keyboard_0.geometry} material={materials.Keyboard} position={[2.5, 0, 19]} />
          <mesh geometry={nodes.Cube_1_4_2_Keyboard_0.geometry} material={materials.Keyboard} position={[5, 0, 19]} />
          <mesh geometry={nodes.Cube_1_5_2_Keyboard_0.geometry} material={materials.Keyboard} position={[-5, 0, 16.765]} />
          <mesh geometry={nodes.Cube_1_6_2_Keyboard_0.geometry} material={materials.Keyboard} position={[-2.5, 0, 16.765]} />
          <mesh geometry={nodes.Cube_1_7_Keyboard_0.geometry} material={materials.Keyboard} position={[0, 0, 16.765]} />
          <mesh geometry={nodes.Cube_1_8_Keyboard_0.geometry} material={materials.Keyboard} position={[2.5, 0, 16.765]} />
          <mesh geometry={nodes.Cube_1_9_Keyboard_0.geometry} material={materials.Keyboard} position={[5, 0, 16.765]} />
          <mesh geometry={nodes.Cube_1_10_Keyboard_0.geometry} material={materials.Keyboard} position={[-5, 0, 14.529]} />
          <mesh geometry={nodes.Cube_1_11_Keyboard_0.geometry} material={materials.Keyboard} position={[-2.5, 0, 14.529]} />
          <mesh geometry={nodes.Cube_1_12_Keyboard_0.geometry} material={materials.Keyboard} position={[0, 0, 14.529]} />
          <mesh geometry={nodes.Cube_1_13_Keyboard_0.geometry} material={materials.Keyboard} position={[2.5, 0, 14.529]} />
          <mesh geometry={nodes.Cube_1_14_Keyboard_0.geometry} material={materials.Keyboard} position={[5, 0, 14.529]} />
          <mesh geometry={nodes.Cube_1_15_Keyboard_0.geometry} material={materials.Keyboard} position={[-5, 0, 12.294]} />
          <mesh geometry={nodes.Cube_1_16_Keyboard_0.geometry} material={materials.Keyboard} position={[-2.5, 0, 12.294]} />
          <mesh geometry={nodes.Cube_1_17_Keyboard_0.geometry} material={materials.Keyboard} position={[0, 0, 12.294]} />
          <mesh geometry={nodes.Cube_1_18_Keyboard_0.geometry} material={materials.Keyboard} position={[2.5, 0, 12.294]} />
          <mesh geometry={nodes.Cube_1_19_Keyboard_0.geometry} material={materials.Keyboard} position={[5, 0, 12.294]} />
          <mesh geometry={nodes.Cube_1_20_Keyboard_0.geometry} material={materials.Keyboard} position={[-5, 0, 10.059]} />
          <mesh geometry={nodes.Cube_1_21_Keyboard_0.geometry} material={materials.Keyboard} position={[-2.5, 0, 10.059]} />
          <mesh geometry={nodes.Cube_1_22_Keyboard_0.geometry} material={materials.Keyboard} position={[0, 0, 10.059]} />
          <mesh geometry={nodes.Cube_1_23_Keyboard_0.geometry} material={materials.Keyboard} position={[2.5, 0, 10.059]} />
          <mesh geometry={nodes.Cube_1_24_Keyboard_0.geometry} material={materials.Keyboard} position={[5, 0, 10.059]} />
          <mesh geometry={nodes.Cube_1_25_Keyboard_0.geometry} material={materials.Keyboard} position={[-5, 0, 7.824]} />
          <mesh geometry={nodes.Cube_1_26_Keyboard_0.geometry} material={materials.Keyboard} position={[-2.5, 0, 7.824]} />
          <mesh geometry={nodes.Cube_1_27_Keyboard_0.geometry} material={materials.Keyboard} position={[0, 0, 7.824]} />
          <mesh geometry={nodes.Cube_1_28_Keyboard_0.geometry} material={materials.Keyboard} position={[2.5, 0, 7.824]} />
          <mesh geometry={nodes.Cube_1_29_Keyboard_0.geometry} material={materials.Keyboard} position={[5, 0, 7.824]} />
          <mesh geometry={nodes.Cube_1_30_Keyboard_0.geometry} material={materials.Keyboard} position={[-5, 0, 5.588]} />
          <mesh geometry={nodes.Cube_1_31_Keyboard_0.geometry} material={materials.Keyboard} position={[-2.5, 0, 5.588]} />
          <mesh geometry={nodes.Cube_1_32_Keyboard_0.geometry} material={materials.Keyboard} position={[0, 0, 5.588]} />
          <mesh geometry={nodes.Cube_1_33_Keyboard_0.geometry} material={materials.Keyboard} position={[2.5, 0, 5.588]} />
          <mesh geometry={nodes.Cube_1_34_Keyboard_0.geometry} material={materials.Keyboard} position={[5, 0, 5.588]} />
          <mesh geometry={nodes.Cube_1_35_Keyboard_0.geometry} material={materials.Keyboard} position={[-5, 0, 3.353]} />
          <mesh geometry={nodes.Cube_1_36_Keyboard_0.geometry} material={materials.Keyboard} position={[-2.5, 0, 3.353]} />
          <mesh geometry={nodes.Cube_1_37_Keyboard_0.geometry} material={materials.Keyboard} position={[0, 0, 3.353]} />
          <mesh geometry={nodes.Cube_1_38_Keyboard_0.geometry} material={materials.Keyboard} position={[2.5, 0, 3.353]} />
          <mesh geometry={nodes.Cube_1_39_Keyboard_0.geometry} material={materials.Keyboard} position={[5, 0, 3.353]} />
          <mesh geometry={nodes.Cube_1_40_Keyboard_0.geometry} material={materials.Keyboard} position={[-5, 0, 1.118]} />
          <mesh geometry={nodes.Cube_1_41_Keyboard_0.geometry} material={materials.Keyboard} position={[-2.5, 0, 1.118]} />
          <mesh geometry={nodes.Cube_1_42_Keyboard_0.geometry} material={materials.Keyboard} position={[0, 0, 1.118]} />
          <mesh geometry={nodes.Cube_1_43_Keyboard_0.geometry} material={materials.Keyboard} position={[2.5, 0, 1.118]} />
          <mesh geometry={nodes.Cube_1_44_Keyboard_0.geometry} material={materials.Keyboard} position={[5, 0, 1.118]} />
          <mesh geometry={nodes.Cube_1_45_Keyboard_0.geometry} material={materials.Keyboard} position={[-5, 0, -1.118]} />
          <mesh geometry={nodes.Cube_1_46_Keyboard_0.geometry} material={materials.Keyboard} position={[-2.5, 0, -1.118]} />
          <mesh geometry={nodes.Cube_1_47_Keyboard_0.geometry} material={materials.Keyboard} position={[0, 0, -1.118]} />
          <mesh geometry={nodes.Cube_1_48_Keyboard_0.geometry} material={materials.Keyboard} position={[2.5, 0, -1.118]} />
          <mesh geometry={nodes.Cube_1_49_Keyboard_0.geometry} material={materials.Keyboard} position={[5, 0, -1.118]} />
          <mesh geometry={nodes.Cube_1_50_Keyboard_0.geometry} material={materials.Keyboard} position={[-5, 0, -3.353]} />
          <mesh geometry={nodes.Cube_1_51_Keyboard_0.geometry} material={materials.Keyboard} position={[-2.5, 0, -3.353]} />
          <mesh geometry={nodes.Cube_1_52_Keyboard_0.geometry} material={materials.Keyboard} position={[0, 0, -3.353]} />
          <mesh geometry={nodes.Cube_1_53_Keyboard_0.geometry} material={materials.Keyboard} position={[2.5, 0, -3.353]} />
          <mesh geometry={nodes.Cube_1_54_Keyboard_0.geometry} material={materials.Keyboard} position={[5, 0, -3.353]} />
          <mesh geometry={nodes.Cube_1_55_Keyboard_0.geometry} material={materials.Keyboard} position={[-5, 0, -5.588]} />
          <mesh geometry={nodes.Cube_1_56_Keyboard_0.geometry} material={materials.Keyboard} position={[-2.5, 0, -5.588]} />
          <mesh geometry={nodes.Cube_1_57_Keyboard_0.geometry} material={materials.Keyboard} position={[0, 0, -5.588]} />
          <mesh geometry={nodes.Cube_1_58_Keyboard_0.geometry} material={materials.Keyboard} position={[2.5, 0, -5.588]} />
          <mesh geometry={nodes.Cube_1_59_Keyboard_0.geometry} material={materials.Keyboard} position={[5, 0, -5.588]} />
          <mesh geometry={nodes.Cube_1_60_Keyboard_0.geometry} material={materials.Keyboard} position={[-5, 0, -7.824]} />
          <mesh geometry={nodes.Cube_1_61_Keyboard_0.geometry} material={materials.Keyboard} position={[-2.5, 0, -7.824]} />
          <mesh geometry={nodes.Cube_1_62_Keyboard_0.geometry} material={materials.Keyboard} position={[0, 0, -7.824]} />
          <mesh geometry={nodes.Cube_1_63_Keyboard_0.geometry} material={materials.Keyboard} position={[2.5, 0, -7.824]} />
          <mesh geometry={nodes.Cube_1_64_Keyboard_0.geometry} material={materials.Keyboard} position={[5, 0, -7.824]} />
          <mesh geometry={nodes.Cube_1_65_Keyboard_0.geometry} material={materials.Keyboard} position={[-5, 0, -10.059]} />
          <mesh geometry={nodes.Cube_1_66_Keyboard_0.geometry} material={materials.Keyboard} position={[-2.5, 0, -10.059]} />
          <mesh geometry={nodes.Cube_1_67_Keyboard_0.geometry} material={materials.Keyboard} position={[0, 0, -10.059]} />
          <mesh geometry={nodes.Cube_1_68_Keyboard_0.geometry} material={materials.Keyboard} position={[2.5, 0, -10.059]} />
          <mesh geometry={nodes.Cube_1_69_Keyboard_0.geometry} material={materials.Keyboard} position={[5, 0, -10.059]} />
          <mesh geometry={nodes.Cube_1_70_Keyboard_0.geometry} material={materials.Keyboard} position={[-5, 0, -12.294]} />
          <mesh geometry={nodes.Cube_1_71_Keyboard_0.geometry} material={materials.Keyboard} position={[-2.5, 0, -12.294]} />
          <mesh geometry={nodes.Cube_1_72_Keyboard_0.geometry} material={materials.Keyboard} position={[0, 0, -12.294]} />
          <mesh geometry={nodes.Cube_1_73_Keyboard_0.geometry} material={materials.Keyboard} position={[2.5, 0, -12.294]} />
          <mesh geometry={nodes.Cube_1_74_Keyboard_0.geometry} material={materials.Keyboard} position={[5, 0, -12.294]} />
          <mesh geometry={nodes.Cube_1_75_Keyboard_0.geometry} material={materials.Keyboard} position={[-5, 0, -14.529]} />
          <mesh geometry={nodes.Cube_1_76_Keyboard_0.geometry} material={materials.Keyboard} position={[-2.5, 0, -14.529]} />
          <mesh geometry={nodes.Cube_1_77_Keyboard_0.geometry} material={materials.Keyboard} position={[0, 0, -14.529]} />
          <mesh geometry={nodes.Cube_1_78_Keyboard_0.geometry} material={materials.Keyboard} position={[2.5, 0, -14.529]} />
          <mesh geometry={nodes.Cube_1_79_Keyboard_0.geometry} material={materials.Keyboard} position={[5, 0, -14.529]} />
          <mesh geometry={nodes.Cube_1_80_Keyboard_0.geometry} material={materials.Keyboard} position={[-5, 0, -16.765]} />
          <mesh geometry={nodes.Cube_1_81_Keyboard_0.geometry} material={materials.Keyboard} position={[-2.5, 0, -16.765]} />
          <mesh geometry={nodes.Cube_1_82_Keyboard_0.geometry} material={materials.Keyboard} position={[0, 0, -16.765]} />
          <mesh geometry={nodes.Cube_1_83_Keyboard_0.geometry} material={materials.Keyboard} position={[2.5, 0, -16.765]} />
          <mesh geometry={nodes.Cube_1_84_Keyboard_0.geometry} material={materials.Keyboard} position={[5, 0, -16.765]} />
          <mesh geometry={nodes.Cube_1_85_Keyboard_0.geometry} material={materials.Keyboard} position={[-5, 0, -19]} />
          <mesh geometry={nodes.Cube_1_86_Keyboard_0.geometry} material={materials.Keyboard} position={[-2.5, 0, -19]} />
          <mesh geometry={nodes.Cube_1_87_Keyboard_0.geometry} material={materials.Keyboard} position={[0, 0, -19]} />
          <mesh geometry={nodes.Cube_1_88_Keyboard_0.geometry} material={materials.Keyboard} position={[2.5, 0, -19]} />
          <mesh geometry={nodes.Cube_1_89_Keyboard_0.geometry} material={materials.Keyboard} position={[5, 0, -19]} />
        </group>
        <mesh geometry={nodes.Cube_2_9_Keyboard_0.geometry} material={materials.Keyboard} position={[-3.47, -1.692, 20.033]} />
        <mesh geometry={nodes.Cube_1_6_Keyboard_0.geometry} material={materials.Keyboard} position={[-3.47, -1.692, -19.868]} />
        <mesh geometry={nodes.Cube_9_Keyboard_0.geometry} material={materials.Keyboard} position={[3.533, 0.171, -0.095]} />
      </group>
      <group position={[-42.327, 43.736, 92.56]} rotation={[0, 0.932, 0]} scale={0.9}>
        <group position={[0.001, -22.995, -4.472]}>
          <mesh geometry={nodes.Cylinder_5_Chair_0.geometry} material={materials.Chair} position={[18.197, 0, 25.483]} />
          <mesh geometry={nodes.Cylinder_4_2_Chair_0.geometry} material={materials.Chair} position={[-18.302, 0, 25.483]} />
          <mesh geometry={nodes.Cylinder_3_2_Chair_0.geometry} material={materials.Chair} position={[-29.146, 0, -9.534]} />
          <mesh geometry={nodes.Cylinder_2_2_Chair_0.geometry} material={materials.Chair} position={[29.253, 0, -9.534]} />
          <mesh geometry={nodes.Cylinder_1_2_Chair_0.geometry} material={materials.Chair} position={[-0.003, 0, -31.899]} />
        </group>
        <group position={[-0.001, -16.422, -4.728]}>
          <mesh geometry={nodes.Cylinder_0_Chair_0.geometry} material={materials.Chair} position={[0, 0, -15]} rotation={[0, Math.PI / 2, 0]} />
          <mesh geometry={nodes.Cylinder_1_3_Chair_0.geometry} material={materials.Chair} position={[14.266, 0, -4.635]} rotation={[0, Math.PI / 10, 0]} />
          <mesh geometry={nodes.Cylinder_2_3_Chair_0.geometry} material={materials.Chair} position={[8.817, 0, 12.135]} rotation={[0, -0.942, 0]} />
          <mesh geometry={nodes.Cylinder_3_3_Chair_0.geometry} material={materials.Chair} position={[-8.817, 0, 12.135]} rotation={[-Math.PI, -0.942, Math.PI]} />
          <mesh geometry={nodes.Cylinder_4_3_Chair_0.geometry} material={materials.Chair} position={[-14.266, 0, -4.635]} rotation={[Math.PI, Math.PI / 10, -Math.PI]} />
        </group>
        <mesh geometry={nodes.Capsule_Chair1_0.geometry} material={materials['Chair.1']} position={[0.644, 62.875, 16.548]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Cube_10_Chair_0.geometry} material={materials.Chair} position={[0.644, 42.162, 20.056]} />
        <mesh geometry={nodes.Sphere_Chair1_0.geometry} material={materials['Chair.1']} position={[-0.001, 21.608, -4.728]} />
        <mesh geometry={nodes.Cylinder_5_2_Chair_0.geometry} material={materials.Chair} position={[-0.001, 2.762, -4.728]} rotation={[0, 0, Math.PI / 2]} />
      </group>
      <group position={[-92.378, 81.548, 2.938]}>
        <group position={[92.378, -62.109, -2.938]}>
          <mesh geometry={nodes.Cube_12_Shelf_0.geometry} material={materials.Shelf} position={[-138.112, 94.16, 4.406]} />
          <mesh geometry={nodes.Cube_1_8_2_Shelf_0.geometry} material={materials.Shelf} position={[-134.042, 94.16, 4.406]} />
        </group>
        <mesh geometry={nodes.Cube_11_Shelf_0.geometry} material={materials.Shelf} position={[-46.189, 25.067, 1.469]} />
        <mesh geometry={nodes.Cube_1_7_2_Shelf_0.geometry} material={materials.Shelf} position={[-46.189, 37.042, 1.469]} />
      </group>
      <group position={[-80, 56.305, 32.69]}>
        <group position={[80, -36.865, -32.69]}>
          <mesh geometry={nodes.Table_4_Table_0.geometry} material={materials.Table} position={[-120, 37.5, 70]} />
          <mesh geometry={nodes.Hole_Table_0.geometry} material={materials.Table} position={[-120, 30, 70]} />
        </group>
        <mesh geometry={nodes.Table_1_2_Table_0.geometry} material={materials.Table} position={[-40, 23.712, -4.621]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Table_2_2_Table_0.geometry} material={materials.Table} position={[-40, 18.178, 37.31]} />
      </group>
      <group position={[6.009, 158.112, 180]}>
        <group position={[-6.009, -138.672, -180]}>
          <mesh geometry={nodes.Frame_Window_0.geometry} material={materials.Window} position={[0, 125, 180]} />
          <mesh geometry={nodes.Hole_2_Window_0.geometry} material={materials.Window} position={[0, 125, 180]} />
        </group>
        <mesh geometry={nodes.Cube_13_Window_0.geometry} material={materials.Window} position={[-5.908, -13.672, 0]} />
        <mesh geometry={nodes.Cube_1_9_2_Window_0.geometry} material={materials.Window} position={[5.908, 13.672, 0]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Glass_Glass_0.geometry} material={materials.Glass} position={[-5.577, -13.486, -0.068]} />
      </group>
      <group position={[0, 19.439, 0]}>
        <mesh geometry={nodes.Room_2_Room_0.geometry} material={materials.Room} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.Window_Hole_Room_0.geometry} material={materials.Room} position={[0, 125, 180]} />
      </group>
      <mesh geometry={nodes.Cube_4_Mat13_0.geometry} material={materials['Mat.13']} position={[-130.928, 115.778, 121.97]} rotation={[0.01, 0.524, -0.005]} />
      <mesh geometry={nodes.Cube_3_Mat13_0.geometry} material={materials['Mat.13_0']} position={[-141.811, 117.391, 81.054]} />
      <mesh geometry={nodes.Plane_Mat12_0.geometry} material={materials['Mat.12']} position={[-98.935, 95.137, 17.692]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Cube_1_Mat10_0.geometry} material={materials['Mat.10']} position={[148.62, 52.581, 31.047]} />
      <mesh geometry={nodes.Cube_2_Mat11_0.geometry} material={materials['Mat.11']} position={[148.62, 65.65, 126.212]} />
    </group>
  )
}

useGLTF.preload('/isometric_room.glb')
